version: '3'
services:

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-volume:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL="mongodb://mongodb:27017/app"
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
      - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
    depends_on:
      - mongodb
    ports:
      - 8888:8081

volumes:
  mongodb-volume:
